name: Build on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    name: macOS Build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake sfml nlohmann-json

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Package
      run: cmake --install build --prefix dist

    - name: Upload app bundle or binary
      uses: actions/upload-artifact@v4
      with:
        name: Ekzeckt-macOS
        path: |
          build/bin/Bundle/Ekzeckt.app
          dist/
